### ISSUE TITLE
[Bug]: 2.7.2 is not a valid SemVer Version

### ISSUE THREAD

**Issue by ADTC** [Shopify/shopify-cli#2063] opened 2022-02-16 11:08 UTC
I'm on Windows, and I updated Shopify CLI from `2.10.0` to `2.11.2`. Then it completely stopped working. I tried downgrading to different versions including `2.10.0`, even uninstalled all the installed versions and installing `2.11.2` again. It still didn't work.

**I'm 100% blocked from doing my work with Shopify CLI.** This line appears to be the culprit:
https://github.com/Shopify/shopify-cli/blob/a89bc74a4547ad8d28cb777beac548608be15f5b/vendor/lib/semantic/version.rb#L15

**Stack Trace:**
```
> shopify
X An unexpected error occured.
        To submit an issue include the stack trace.

Traceback (most recent call last):
        27: from C:/Ruby27-x64/bin/shopify:23:in `<main>'
        26: from C:/Ruby27-x64/bin/shopify:23:in `load'
        25: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.2/bin/shopify:56:in `<top (required)>'
        24: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.2/bin/shopify:45:in `block in <top (required)>'
        23: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.2/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        22: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.2/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        21: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.2/bin/shopify:46:in `block (2 levels) in <top (required)>'
        20: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.2/lib/shopify_cli/core/entry_point.rb:23:in `call'
        19: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.2/lib/shopify_cli/core/monorail.rb:30:in `log'
        18: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.2/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
        17: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.2/lib/shopify_cli/core/executor.rb:15:in `call'
        16: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        15: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        14: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        13: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        12: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        11: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.2/lib/shopify_cli/core/executor.rb:16:in `block in call'
        10: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
         9: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.2/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
         8: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
         7: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.2/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
         6: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
         5: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.2/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
         4: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.2/lib/shopify_cli/command.rb:32:in `call'
         3: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.2/lib/shopify_cli/command.rb:82:in `check_ruby_version'
         2: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.2/lib/shopify_cli/environment.rb:18:in `ruby_version'
         1: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.2/lib/shopify_cli/environment.rb:18:in `new'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.2/vendor/lib/semantic/version.rb:15:in `initialize': Initializing... (ArgumentError)
2.7.2 is not a valid SemVer Version (http://semver.org)
```

_**PS:** Mentioned in #2039_
_**CC:** @gonzaloriestra_

**Comment by ADTC** [comment] 2022-02-16 12:33
Does it appear related to the Ruby version?

```
> ruby -v
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x64-mingw32]
```

**Comment by gonzaloriestra** [comment] 2022-02-22 15:22
I don't understand what could be happening and I'm not able to reproduce it (I'm also testing with Windows x64 and Ruby 2.7.2)...

Regarding your suggestion, we are calling [chomp](https://apidock.com/ruby/String/chomp) to remove that line break here:
https://github.com/Shopify/shopify-cli/blob/a47e7c0a6ac38e04f2c483d9d4d0054f2172fbc6/lib/shopify_cli/environment.rb#L18

Would you mind opening `C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.2/lib/shopify_cli/environment.rb` and replacing the `ruby_version` method with this one? And then, try `shopify` again.

```ruby
def self.ruby_version(context: Context.new)
  out, err, stat = context.capture3("ruby", "-v")
  raise ShopifyCLI::Abort, err unless stat.success?
  version = out.scan(/ruby \d+\.\d+\.\d+/).first.split(" ").last
  ::Semantic::Version.new(version)
end
```

**Comment by ADTC** [comment] 2022-02-22 15:56
**AHA!!!** This problem only occurs on my computer!

I have a start-up script on my Command Prompt (like `.bashrc` but for Windows) and I put an `echo Initializing...` in there to know that it worked... So now when you run `ruby -e "puts RUBY_VERSION"` and just capture all the output without any pattern match, **in my computer,** you'll get:

```
Initializing...
2.7.2
```
Obviously SemVer can't understand that. _(Look carefully, and you'll notice it in my stack trace above!)_

The best news is, your _new version_ of the method works perfectly because you're specifically capturing the version string using a regex pattern match. So it wouldn't matter whatever comes before or after it.

Even though this is a super rare case, I hope you'd consider updating `ruby_version` anyway. I suggest to keep the command as `ruby -e "puts RUBY_VERSION"` but do a simple pattern matching:

```ruby
    def self.ruby_version(context: Context.new)
      out, err, stat = context.capture3('ruby -e "puts RUBY_VERSION"')
      raise ShopifyCLI::Abort, err unless stat.success?
      version = out.scan(/\d+\.\d+\.\d+/).first
      ::Semantic::Version.new(version)
    end
```

This also works. Less code change.

**Comment by gonzaloriestra** [comment] 2022-02-22 16:23
Great! I'll better replace that method then.

**Comment by gonzaloriestra** [comment] 2022-02-24 15:16
Oh, thanks a lot for your contribution! But I've just opened [another PR](https://github.com/Shopify/shopify-cli/pull/2086) including other similar improvements, so I guess you can close it.

It will probably be included in the next release.

**Closed** 2022-03-16 10:09 UTC
Labels: type:bug, area:core-cli
