### ISSUE TITLE
CLI is not detecting any local changes when running shopify theme serve

### ISSUE THREAD

**Issue by dungle-scrubs** [Shopify/shopify-cli#1450] opened 2021-08-13 08:36 UTC
# Issue summary

When I run `shopify-theme-serve`, any changes made to the code aren't updated in the browser.

## Expected behavior

I'm not sure what to expect as it's my first time using it.

## Actual behavior

Changes aren't updated and I don't see any change or activity in the CLI.  The CLI doesn't seem to be picking up changes.

## Steps to reproduce the problem

I just followed the [tutorial](https://shopify.dev/themes/tools/cli/getting-started) in the Shopify docs.

## Specifications

- App type: Theme
- Operating System: Mac OS v11.5.2
- Shell: zsh
- Ruby version (ruby -v): 3.0.2p107

**Comment by GuillermoCasanova** [comment] 2021-08-15 21:49
Similar issue here, but only with HTML / liquid files. Changes are only seen on HTML/liquid files after saving twice or manually refreshing. CSS and JS changes happen as expected.

**Comment by macournoyer** [comment] 2021-11-03 14:58
Closing as duplicate of #1409

**Closed by macournoyer** 2021-11-03 14:58 UTC
Labels: area:theme
