### ISSUE TITLE
Unable to authenticate

### ISSUE THREAD

**Issue by rome2o** [Shopify/shopify-cli#1320] opened 2021-06-30 17:32 UTC
## Issue summary

So basically, I'm trying to login using the following command and need to populate products and serve the theme.

`shopify login --store=my-store.myshopify.com`

(Weird thing, you are able to authenticate to that dummy store even if you don't have it)

I ran the above command with the right store and I am authenticated. However, no other commands seems to understand that I have authenticated.

`shopify populate products`

## Expected behavior

It should populate products

## Actual behavior

I get the following error

`✗ You are not authorized to edit themes on deardawn.myshopify.com.
Make sure you are a user of that store, and allowed to edit themes`

## Steps to reproduce the problem

1. Be a Shopify Partner
1. Login with `shopify login --store=yourstore.myshopify.com`
1. Populate products with `shopify populate products`

## Specifications

- App type: n.a
- Operating System: macOS High Sierra
- Shell: zsh
- Ruby version (ruby -v): ruby 2.7.0p0

**Comment by macournoyer** [comment] 2021-07-06 19:23
Closing as a duplicate of #1309.

Login in through https://deardawn.myshopify.com/admin in your browser once should fix the issue.

**Closed by macournoyer** 2021-07-06 19:23 UTC
