### ISSUE TITLE
Liquid reloads before file synced to server

### ISSUE THREAD

**Issue by bigskillet** [Shopify/shopify-cli#1597] opened 2021-09-30 13:59 UTC
# Issue summary

When making edits to `.liquid` files, the browser reloads immediately, instead of waiting for the file to sync to the server. You have to reload the browser 2-3 times to see the change. **_It has made development unbearable!_**

I'd like to bring attention to this [hot-reload thread](https://github.com/Shopify/shopify-cli/issues/1409), where there is a PR that may have solved the syncing issue.

## Expected behavior

Reload browser **_after_** changes have synced to server.

## Actual behavior

Browser reloads immediately, instead of waiting for changes to sync.

## Steps to reproduce the problem

1. Edit `.liquid` file
2. Browser reloads immediately
3. Refresh browser 2-3 times to see changes
4. Repeat process for every... single... edit...

**Comment by GuillermoCasanova** [comment] 2021-10-22 02:53
Second this. Hot Reload is only working for CSS files. Liquid and JS requires a reload. It's a pain.

**Comment by macournoyer** [comment] 2021-11-08 18:57
Sorry about that! There is clearly a bug w/ `theme serve` here on some machines (that I've been unable to reproduce yet).

The whole point of `theme serve` was to have fast updates of Liquid files. You shouldn't have to wait for our server to update the Liquid file or anything like that, it should be instant, always. What I mean is that it should work as you're describing, but obviously it isn't for a few people, and I'm trying to understand why.

I'll close this issue in favor of this one: https://github.com/Shopify/shopify-cli/issues/1409.

**Closed by macournoyer** 2021-11-08 18:57 UTC
Labels: area:theme
