### ISSUE TITLE
can't use "shopify create"

### ISSUE THREAD

**Issue by Juan321654** [Shopify/shopify-cli#1115] opened 2021-03-10 00:03 UTC
# Issue summary
I cant use "Shopify create"

I type "Shopify create" and it lets me chose Node,js, then the name of the app, and when it gives me the option to chose between a private or public app and I chose one. it gives the error

## Expected behavior
create the app

## Actual behavior
↓ getting the following error ↓

<details>Traceback (most recent call last):
        51: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/bin/shopify:32:in `<main>'
        50: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        49: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        48: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/bin/shopify:33:in `block in <main>'
        47: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/core/entry_point.rb:42:in `call'
        46: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/core/monorail.rb:32:in `log'
        45: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/core/entry_point.rb:43:in `block in call'
        44: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/core/executor.rb:15:in `call'
        43: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
        42: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        41: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        40: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        39: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        38: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        37: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
        36: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        35: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
        34: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
        33: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
        32: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
        31: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
        30: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/commands/create.rb:8:in `call'
        29: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/command.rb:25:in `call'
        28: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/commands/create.rb:25:in `call'
        27: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/sub_command.rb:12:in `call'
        26: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/project_types/node/commands/create.rb:16:in `call'
        25: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/form.rb:13:in `ask'
        24: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/project_types/node/forms/create.rb:13:in `ask'
        23: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/task.rb:7:in `call'
        22: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/tasks/select_org_and_shop.rb:14:in `call'
        21: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/tasks/select_org_and_shop.rb:42:in `get_organization'
        20: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/tasks/select_org_and_shop.rb:31:in `organizations'
        19: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/partners_api/organizations.rb:6:in `fetch_all'
        18: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/partners_api.rb:48:in `query'
        17: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/partners_api.rb:63:in `authenticated_req'
        16: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/partners_api.rb:49:in `block in query'
        15: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/api.rb:26:in `query'
        14: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/api.rb:69:in `request'
        13: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
        12: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/api.rb:46:in `block in request'
        11: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/api.rb:96:in `default_headers'
        10: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/api.rb:91:in `current_sha'
         9: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/git.rb:24:in `sha'
         8: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/git.rb:118:in `rev_parse'
         7: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/git.rb:112:in `exec'
         6: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/context.rb:404:in `capture3'
         5: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/system.rb:90:in `capture3'
         4: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/system.rb:194:in `delegate_open3'
         3: from C:/Ruby27-x64/lib/ruby/2.7.0/open3.rb:281:in `capture3'
         2: from C:/Ruby27-x64/lib/ruby/2.7.0/open3.rb:101:in `popen3'
         1: from C:/Ruby27-x64/lib/ruby/2.7.0/open3.rb:213:in `popen_run'
C:/Ruby27-x64/lib/ruby/2.7.0/open3.rb:213:in `spawn': No such file or directory - git (Errno::ENOENT)</details>

## Steps to reproduce the problem

1. shopify create command
1.
1.

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

## Specifications

- App type: node js > public
- Operating System: windows 10
- Shell: Start command prompt with Ruby
- Ruby version (ruby -v): ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x64-mingw32]

**Comment by mllemango** [comment] 2021-03-10 03:39
Hey @Juan321654, it looks like the error is caused by not having git installed. Can you install git and try again?

**Comment by Juan321654** [comment] 2021-03-10 03:48
> Hey @Juan321654, it looks like the error is caused by not having git installed. Can you install git and try again?

I already have it installed and it works fine when doing other apps like react, etc, but I re-installed it to make sure but did not fix the issue.

**Comment by ronneysingh** [comment] 2021-04-16 18:35
@Juan321654 , I was facing similar issue. This might help you - https://github.com/Shopify/shopify-app-cli/issues/1171#issuecomment-821430512

**Comment by mkevinosullivan** [comment] 2021-08-03 17:57
👋🏻 As there hasn't been any update on this issue for almost three months, I'm going to close it. If this issue still exists, please re-open it.

**Closed** 2022-04-02 03:39 UTC
Labels: area:dev-environment, no-issue-activity
