### ISSUE TITLE
[Bug] Error installing rails gem

### ISSUE THREAD

**Issue by bparanj** [Shopify/shopify-cli#2080] opened 2022-02-21 19:49 UTC
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

app

### Expected behavior

Rails 7 must be installed

### Actual behavior

It fails to install Rails 7 with error:

┃ ✗ Error installing rails gem

### Stack trace

```shell
No stack trace only Error message.
```

### Reproduction steps

1. Run: shopify app create rails
2. Pick the project name and mysql as the database
3. It fails with the shown error

### Operating System

Mac OS Monterey 12.2.1 (21D62)

### CLI version (run `shopify version` if you're not sure)

2.11.2

### Shell

zsh

### Ruby version (run `ruby -v` if you're not sure)

ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [arm64-darwin21]

### What language and version are you using in your application?

Ruby 3.0.3

**Comment by gonzaloriestra** [comment] 2022-02-22 14:23
Hi! I'm not able to reproduce the issue, could you please run `SHOPIFY_CLI_STACKTRACE=1 shopify app create rails` and share the full log?

Have you tried manually running `gem install rails`?

**Comment by DiamessoGroup** [comment] 2022-05-28 01:06
I am getting the same error
`Error installing rails gem`


Using development store test-app-kcd.myshopify.com
? Would you like to select what database type to use now? (SQLite is the default)
If you want to change this in the future, run rails db:system:change --to=[new_db_type]. For more info:
https://gorails.com/episodes/rails-6-db-system-change-command
? Would you like to select what database type to use now? (SQLite is the default)
If you want to change this in the future, run rails db:system:change --to=[new_db_type]. For more info:
https://gorails.com/episodes/rails-6-db-system-change-command
 (You chose: no)
✓ node v18.2.0
✓ yarn 1.22.19
┏━━ Generating new rails app project in rails-2.0… ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃       create
┃       create  README.md
┃       create  Rakefile
┃       create  .ruby-version
┃       create  config.ru
┃       create  .gitignore
┃       create  .gitattributes
┃       create  Gemfile
┃          run  git init from "."
┃ hint: Using 'master' as the name for the initial branch. This default branch name
┃ hint: is subject to change. To configure the initial branch name to use in all
┃ hint: of your new repositories, which will suppress this warning, call:
┃ hint:
┃ hint: 	git config --global init.defaultBranch <name>
┃ hint:
┃ hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
┃ hint: 'development'. The just-created branch can be renamed via this command:
┃ hint:
┃ hint: 	git branch -m <name>
┃ Initialized empty Git repository in /Volumes/GoogleDrive-114963156304886504282/My Drive/Shopify Projects Development/Test-Project/rails-2.0/.git/
┃       create  app
┃       create  app/assets/config/manifest.js
┃       create  app/assets/stylesheets/application.css
┃       create  app/channels/application_cable/channel.rb
┃       create  app/channels/application_cable/connection.rb
┃       create  app/controllers/application_controller.rb
┃       create  app/helpers/application_helper.rb
┃       create  app/jobs/application_job.rb
┃       create  app/mailers/application_mailer.rb
┃       create  app/models/application_record.rb
┃       create  app/views/layouts/application.html.erb
┃       create  app/views/layouts/mailer.html.erb
┃       create  app/views/layouts/mailer.text.erb
┃       create  app/assets/images
┃       create  app/assets/images/.keep
┃       create  app/controllers/concerns/.keep
┃       create  app/models/concerns/.keep
┃       create  bin
┃       create  bin/rails
┃       create  bin/rake
┃       create  bin/setup
┃       create  config
┃       create  config/routes.rb
┃       create  config/application.rb
┃       create  config/environment.rb
┃       create  config/cable.yml
┃       create  config/puma.rb
┃       create  config/storage.yml
┃       create  config/environments
┃       create  config/environments/development.rb
┃       create  config/environments/production.rb
┃       create  config/environments/test.rb
┃       create  config/initializers
┃       create  config/initializers/assets.rb
┃       create  config/initializers/content_security_policy.rb
┃       create  config/initializers/cors.rb
┃       create  config/initializers/filter_parameter_logging.rb
┃       create  config/initializers/inflections.rb
┃       create  config/initializers/new_framework_defaults_7_0.rb
┃       create  config/initializers/permissions_policy.rb
┃       create  config/locales
┃       create  config/locales/en.yml
┃       create  config/master.key
┃       append  .gitignore
┃       create  config/boot.rb
┃       create  config/database.yml
┃       create  db
┃       create  db/seeds.rb
┃       create  lib
┃       create  lib/tasks
┃       create  lib/tasks/.keep
┃       create  lib/assets
┃       create  lib/assets/.keep
┃       create  log
┃       create  log/.keep
┃       create  public
┃       create  public/404.html
┃       create  public/422.html
┃       create  public/500.html
┃       create  public/apple-touch-icon-precomposed.png
┃       create  public/apple-touch-icon.png
┃       create  public/favicon.ico
┃       create  public/robots.txt
┃       create  tmp
┃       create  tmp/.keep
┃       create  tmp/pids
┃       create  tmp/pids/.keep
┃       create  tmp/cache
┃       create  tmp/cache/assets
┃       create  vendor
┃       create  vendor/.keep
┃       create  test/fixtures/files
┃       create  test/fixtures/files/.keep
┃       create  test/controllers
┃       create  test/controllers/.keep
┃       create  test/mailers
┃       create  test/mailers/.keep
┃       create  test/models
┃       create  test/models/.keep
┃       create  test/helpers
┃       create  test/helpers/.keep
┃       create  test/integration
┃       create  test/integration/.keep
┃       create  test/channels/application_cable/connection_test.rb
┃       create  test/test_helper.rb
┃       create  test/system
┃       create  test/system/.keep
┃       create  test/application_system_test_case.rb
┃       create  storage
┃       create  storage/.keep
┃       create  tmp/storage
┃       create  tmp/storage/.keep
┃       remove  config/initializers/cors.rb
┃       remove  config/initializers/new_framework_defaults_7_0.rb
┃          run  bundle install
┃ Fetching gem metadata from https://rubygems.org/...........
┃ Resolving dependencies.......
┃ Using rake 13.0.6
┃ Using concurrent-ruby 1.1.10
┃ Using minitest 5.15.0
┃ Using builder 3.2.4
┃ Using erubi 1.10.0
┃ Using racc 1.6.0
┃ Using crass 1.0.6
┃ Using rack 2.2.3.1
┃ Using nio4r 2.5.8
┃ Using websocket-extensions 0.1.5
┃ Using marcel 1.0.2
┃ Using mini_mime 1.1.2
┃ Using digest 3.1.0
┃ Using timeout 0.3.0
┃ Using public_suffix 4.0.7
┃ Using strscan 3.0.3
┃ Using bundler 2.3.14
┃ Using bindex 0.8.1
┃ Using msgpack 1.5.2
┃ Using matrix 0.4.2
┃ Using regexp_parser 2.5.0
┃ Using io-console 0.5.11
┃ Using childprocess 4.1.0
┃ Using method_source 1.0.0
┃ Using thor 1.2.1
┃ Using zeitwerk 2.5.4
┃ Using rexml 3.2.5
┃ Using rubyzip 2.3.2
┃ Using websocket 1.2.9
┃ Using sqlite3 1.4.2
┃ Using i18n 1.10.0
┃ Using tzinfo 2.0.4
┃ Using nokogiri 1.13.6 (x86_64-darwin)
┃ Using websocket-driver 0.7.5
┃ Using net-protocol 0.1.3
┃ Using puma 5.6.4
┃ Using bootsnap 1.11.1
┃ Using activesupport 7.0.3
┃ Using loofah 2.18.0
┃ Using rack-test 1.1.0
┃ Using mail 2.7.1
┃ Using net-imap 0.2.3
┃ Using net-pop 0.1.1
┃ Using net-smtp 0.3.1
┃ Using addressable 2.8.0
┃ Using xpath 3.2.0
┃ Using reline 0.3.1
┃ Using selenium-webdriver 4.2.0
┃ Using sprockets 4.0.3
┃ Using irb 1.4.1
┃ Using webdrivers 5.0.0
┃ Using rails-dom-testing 2.0.3
┃ Using rails-html-sanitizer 1.4.2
┃ Using globalid 1.0.0
┃ Using activemodel 7.0.3
┃ Using capybara 3.37.1
┃ Using actionview 7.0.3
┃ Using activejob 7.0.3
┃ Using activerecord 7.0.3
┃ Using debug 1.5.0
┃ Using actionpack 7.0.3
┃ Using jbuilder 2.11.5
┃ Using actioncable 7.0.3
┃ Using activestorage 7.0.3
┃ Using actionmailer 7.0.3
┃ Using railties 7.0.3
┃ Using sprockets-rails 3.4.2
┃ Using actionmailbox 7.0.3
┃ Using actiontext 7.0.3
┃ Using importmap-rails 1.1.0
┃ Using stimulus-rails 1.0.4
┃ Using turbo-rails 1.1.1
┃ Using web-console 4.2.0
┃ Using rails 7.0.3
┃ Bundle complete! 15 Gemfile dependencies, 74 gems now installed.
┃ Use `bundle info [gemname]` to see where a bundled gem is installed.
┃          run  bundle binstubs bundler
┃        rails  importmap:install
┃ /usr/local/Cellar/shopify-cli/2.17.0/gems/msgpack-1.5.2/lib/msgpack.rb:7:in `require': incompatible library version - /usr/local/Cellar/shopify-cli/2.17.0/gems/msgpack-1.5.2/lib/msgpack/msgpack.bundle (LoadError)
┃ 	from /usr/local/Cellar/shopify-cli/2.17.0/gems/msgpack-1.5.2/lib/msgpack.rb:7:in `<top (required)>'
┃ 	from /usr/local/Cellar/shopify-cli/2.17.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/store.rb:5:in `require'
┃ 	from /usr/local/Cellar/shopify-cli/2.17.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/store.rb:5:in `block in <top (required)>'
┃ 	from /usr/local/Cellar/shopify-cli/2.17.0/gems/bootsnap-1.11.1/lib/bootsnap/explicit_require.rb:45:in `rescue in with_gems'
┃ 	from /usr/local/Cellar/shopify-cli/2.17.0/gems/bootsnap-1.11.1/lib/bootsnap/explicit_require.rb:41:in `with_gems'
┃ 	from /usr/local/Cellar/shopify-cli/2.17.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/store.rb:5:in `<top (required)>'
┃ 	from /usr/local/Cellar/shopify-cli/2.17.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache.rb:54:in `require_relative'
┃ 	from /usr/local/Cellar/shopify-cli/2.17.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache.rb:54:in `<top (required)>'
┃ 	from /usr/local/Cellar/shopify-cli/2.17.0/gems/bootsnap-1.11.1/lib/bootsnap.rb:5:in `require_relative'
┃ 	from /usr/local/Cellar/shopify-cli/2.17.0/gems/bootsnap-1.11.1/lib/bootsnap.rb:5:in `<top (required)>'
┃ 	from /usr/local/Cellar/shopify-cli/2.17.0/gems/bootsnap-1.11.1/lib/bootsnap/setup.rb:3:in `require_relative'
┃ 	from /usr/local/Cellar/shopify-cli/2.17.0/gems/bootsnap-1.11.1/lib/bootsnap/setup.rb:3:in `<top (required)>'
┃ 	from /Volumes/GoogleDrive-114963156304886504282/My Drive/Shopify Projects Development/Test-Project/rails-2.0/config/boot.rb:4:in `require'
┃ 	from /Volumes/GoogleDrive-114963156304886504282/My Drive/Shopify Projects Development/Test-Project/rails-2.0/config/boot.rb:4:in `<top (required)>'
┃ 	from bin/rails:3:in `require_relative'
┃ 	from bin/rails:3:in `<main>'
┃ /usr/local/Cellar/shopify-cli/2.17.0/gems/msgpack-1.5.2/lib/msgpack.rb:7:in `require': incompatible library version - /usr/local/Cellar/shopify-cli/2.17.0/gems/msgpack-1.5.2/lib/msgpack/msgpack.bundle (LoadError)
┃ 	from /usr/local/Cellar/shopify-cli/2.17.0/gems/msgpack-1.5.2/lib/msgpack.rb:7:in `<top (required)>'
┃ 	from /usr/local/Cellar/shopify-cli/2.17.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/store.rb:5:in `require'
┃ 	from /usr/local/Cellar/shopify-cli/2.17.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/store.rb:5:in `block in <top (required)>'
┃ 	from /usr/local/Cellar/shopify-cli/2.17.0/gems/bootsnap-1.11.1/lib/bootsnap/explicit_require.rb:42:in `with_gems'
┃ 	from /usr/local/Cellar/shopify-cli/2.17.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/store.rb:5:in `<top (required)>'
┃ 	from /usr/local/Cellar/shopify-cli/2.17.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache.rb:54:in `require_relative'
┃ 	from /usr/local/Cellar/shopify-cli/2.17.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache.rb:54:in `<top (required)>'
┃ 	from /usr/local/Cellar/shopify-cli/2.17.0/gems/bootsnap-1.11.1/lib/bootsnap.rb:5:in `require_relative'
┃ 	from /usr/local/Cellar/shopify-cli/2.17.0/gems/bootsnap-1.11.1/lib/bootsnap.rb:5:in `<top (required)>'
┃ 	from /usr/local/Cellar/shopify-cli/2.17.0/gems/bootsnap-1.11.1/lib/bootsnap/setup.rb:3:in `require_relative'
┃ 	from /usr/local/Cellar/shopify-cli/2.17.0/gems/bootsnap-1.11.1/lib/bootsnap/setup.rb:3:in `<top (required)>'
┃ 	from /Volumes/GoogleDrive-114963156304886504282/My Drive/Shopify Projects Development/Test-Project/rails-2.0/config/boot.rb:4:in `require'
┃ 	from /Volumes/GoogleDrive-114963156304886504282/My Drive/Shopify Projects Development/Test-Project/rails-2.0/config/boot.rb:4:in `<top (required)>'
┃ 	from bin/rails:3:in `require_relative'
┃ 	from bin/rails:3:in `<main>'
┃        rails  turbo:install stimulus:install
┃ /usr/local/Cellar/shopify-cli/2.17.0/gems/msgpack-1.5.2/lib/msgpack.rb:7:in `require': incompatible library version - /usr/local/Cellar/shopify-cli/2.17.0/gems/msgpack-1.5.2/lib/msgpack/msgpack.bundle (LoadError)
┃ 	from /usr/local/Cellar/shopify-cli/2.17.0/gems/msgpack-1.5.2/lib/msgpack.rb:7:in `<top (required)>'
┃ 	from /usr/local/Cellar/shopify-cli/2.17.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/store.rb:5:in `require'
┃ 	from /usr/local/Cellar/shopify-cli/2.17.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/store.rb:5:in `block in <top (required)>'
┃ 	from /usr/local/Cellar/shopify-cli/2.17.0/gems/bootsnap-1.11.1/lib/bootsnap/explicit_require.rb:45:in `rescue in with_gems'
┃ 	from /usr/local/Cellar/shopify-cli/2.17.0/gems/bootsnap-1.11.1/lib/bootsnap/explicit_require.rb:41:in `with_gems'
┃ 	from /usr/local/Cellar/shopify-cli/2.17.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/store.rb:5:in `<top (required)>'
┃ 	from /usr/local/Cellar/shopify-cli/2.17.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache.rb:54:in `require_relative'
┃ 	from /usr/local/Cellar/shopify-cli/2.17.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache.rb:54:in `<top (required)>'
┃ 	from /usr/local/Cellar/shopify-cli/2.17.0/gems/bootsnap-1.11.1/lib/bootsnap.rb:5:in `require_relative'
┃ 	from /usr/local/Cellar/shopify-cli/2.17.0/gems/bootsnap-1.11.1/lib/bootsnap.rb:5:in `<top (required)>'
┃ 	from /usr/local/Cellar/shopify-cli/2.17.0/gems/bootsnap-1.11.1/lib/bootsnap/setup.rb:3:in `require_relative'
┃ 	from /usr/local/Cellar/shopify-cli/2.17.0/gems/bootsnap-1.11.1/lib/bootsnap/setup.rb:3:in `<top (required)>'
┃ 	from /Volumes/GoogleDrive-114963156304886504282/My Drive/Shopify Projects Development/Test-Project/rails-2.0/config/boot.rb:4:in `require'
┃ 	from /Volumes/GoogleDrive-114963156304886504282/My Drive/Shopify Projects Development/Test-Project/rails-2.0/config/boot.rb:4:in `<top (required)>'
┃ 	from bin/rails:3:in `require_relative'
┃ 	from bin/rails:3:in `<main>'
┃ /usr/local/Cellar/shopify-cli/2.17.0/gems/msgpack-1.5.2/lib/msgpack.rb:7:in `require': incompatible library version - /usr/local/Cellar/shopify-cli/2.17.0/gems/msgpack-1.5.2/lib/msgpack/msgpack.bundle (LoadError)
┃ 	from /usr/local/Cellar/shopify-cli/2.17.0/gems/msgpack-1.5.2/lib/msgpack.rb:7:in `<top (required)>'
┃ 	from /usr/local/Cellar/shopify-cli/2.17.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/store.rb:5:in `require'
┃ 	from /usr/local/Cellar/shopify-cli/2.17.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/store.rb:5:in `block in <top (required)>'
┃ 	from /usr/local/Cellar/shopify-cli/2.17.0/gems/bootsnap-1.11.1/lib/bootsnap/explicit_require.rb:42:in `with_gems'
┃ 	from /usr/local/Cellar/shopify-cli/2.17.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/store.rb:5:in `<top (required)>'
┃ 	from /usr/local/Cellar/shopify-cli/2.17.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache.rb:54:in `require_relative'
┃ 	from /usr/local/Cellar/shopify-cli/2.17.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache.rb:54:in `<top (required)>'
┃ 	from /usr/local/Cellar/shopify-cli/2.17.0/gems/bootsnap-1.11.1/lib/bootsnap.rb:5:in `require_relative'
┃ 	from /usr/local/Cellar/shopify-cli/2.17.0/gems/bootsnap-1.11.1/lib/bootsnap.rb:5:in `<top (required)>'
┃ 	from /usr/local/Cellar/shopify-cli/2.17.0/gems/bootsnap-1.11.1/lib/bootsnap/setup.rb:3:in `require_relative'
┃ 	from /usr/local/Cellar/shopify-cli/2.17.0/gems/bootsnap-1.11.1/lib/bootsnap/setup.rb:3:in `<top (required)>'
┃ 	from /Volumes/GoogleDrive-114963156304886504282/My Drive/Shopify Projects Development/Test-Project/rails-2.0/config/boot.rb:4:in `require'
┃ 	from /Volumes/GoogleDrive-114963156304886504282/My Drive/Shopify Projects Development/Test-Project/rails-2.0/config/boot.rb:4:in `<top (required)>'
┃ 	from bin/rails:3:in `require_relative'
┃ 	from bin/rails:3:in `<main>'
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (7.74s) ━━
✓ Adding shopify_app gem…
┏━━ Running bundle install… ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ Fetching gem metadata from https://rubygems.org/..........
┃ Resolving dependencies....
┃ Using rake 13.0.6
┃ Using erubi 1.10.0
┃ Using crass 1.0.6
┃ Using rack 2.2.3.1
┃ Using websocket-extensions 0.1.5
┃ Using marcel 1.0.2
┃ Using digest 3.1.0
┃ Using concurrent-ruby 1.1.10
┃ Using minitest 5.15.0
┃ Using builder 3.2.4
┃ Using racc 1.6.0
┃ Using nio4r 2.5.8
┃ Using mini_mime 1.1.2
┃ Using bundler 2.3.14
┃ Using timeout 0.3.0
┃ Using strscan 3.0.3
┃ Using public_suffix 4.0.7
┃ Using io-console 0.5.11
┃ Using bindex 0.8.1
┃ Using mime-types-data 3.2022.0105
┃ Using multi_xml 0.6.0
┃ Using msgpack 1.5.2
┃ Using browser_sniffer 1.4.0
┃ Using matrix 0.4.2
┃ Using regexp_parser 2.5.0
┃ Using childprocess 4.1.0
┃ Using hash_diff 1.0.0
┃ Using method_source 1.0.0
┃ Using thor 1.2.1
┃ Using oj 3.13.13
┃ Using openssl 3.0.0
┃ Using zeitwerk 2.5.4
┃ Using websocket 1.2.9
┃ Using jwt 2.3.0
┃ Using rexml 3.2.5
┃ Using sorbet-runtime 0.5.10032
┃ Using rubyzip 2.3.2
┃ Using securerandom 0.2.0
┃ Using sqlite3 1.4.2
┃ Using i18n 1.10.0
┃ Using tzinfo 2.0.4
┃ Using rack-test 1.1.0
┃ Using websocket-driver 0.7.5
┃ Using sprockets 4.0.3
┃ Using nokogiri 1.13.6 (x86_64-darwin)
┃ Using net-protocol 0.1.3
┃ Using addressable 2.8.0
┃ Using reline 0.3.1
┃ Using mime-types 3.4.1
┃ Using bootsnap 1.11.1
┃ Using puma 5.6.4
┃ Using irb 1.4.1
┃ Using mail 2.7.1
┃ Using selenium-webdriver 4.2.0
┃ Using activesupport 7.0.3
┃ Using httparty 0.20.0
┃ Using loofah 2.18.0
┃ Using rails-dom-testing 2.0.3
┃ Using net-imap 0.2.3
┃ Using net-pop 0.1.1
┃ Using net-smtp 0.3.1
┃ Using xpath 3.2.0
┃ Using debug 1.5.0
┃ Using webdrivers 5.0.0
┃ Using globalid 1.0.0
┃ Using activemodel 7.0.3
┃ Using rails-html-sanitizer 1.4.2
┃ Using actionview 7.0.3
┃ Using capybara 3.37.1
┃ Using actionpack 7.0.3
┃ Using activejob 7.0.3
┃ Using activerecord 7.0.3
┃ Using jbuilder 2.11.5
┃ Using shopify_api 10.1.0
┃ Using activemodel-serializers-xml 1.0.2
┃ Using redirect_safely 1.0.0
┃ Using actioncable 7.0.3
┃ Using activestorage 7.0.3
┃ Using actionmailer 7.0.3
┃ Using railties 7.0.3
┃ Using sprockets-rails 3.4.2
┃ Using activeresource 6.0.0
┃ Using actionmailbox 7.0.3
┃ Using actiontext 7.0.3
┃ Using importmap-rails 1.1.0
┃ Using stimulus-rails 1.0.4
┃ Using turbo-rails 1.1.1
┃ Using web-console 4.2.0
┃ Using rails 7.0.3
┃ Using shopify_app 19.0.2
┃ Bundle complete! 16 Gemfile dependencies, 90 gems now installed.
┃ Use `bundle info [gemname]` to see where a bundled gem is installed.
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (3.43s) ━━
┏━━ Running shopify_app generator… ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃     generate  shopify_app:install --new-shopify-cli-app
┃        rails  generate shopify_app:install --new-shopify-cli-app
┃       create  config/initializers/shopify_app.rb
┃       create  config/initializers/session_store.rb
┃       create  app/views/layouts/embedded_app.html.erb
┃       create  app/views/layouts/_flash_messages.html.erb
┃       create  app/assets/javascripts/shopify_app.js
┃       create  app/assets/javascripts/flash_messages.js
┃        route  mount ShopifyApp::Engine, at: '/'
┃       insert  config/environments/development.rb
┃     generate  shopify_app:shop_model --new-shopify-cli-app
┃        rails  generate shopify_app:shop_model --new-shopify-cli-app
┃       create  app/models/shop.rb
┃       create  db/migrate/20220528005747_create_shops.rb
┃       create  db/migrate/20220528005748_add_shop_access_scopes_column.rb
┃         gsub  config/initializers/shopify_app.rb
┃       create  test/fixtures/shops.yml
┃     generate  shopify_app:authenticated_controller
┃        rails  generate shopify_app:authenticated_controller
┃       create  app/controllers/authenticated_controller.rb
┃     generate  shopify_app:home_controller --new-shopify-cli-app
┃        rails  generate shopify_app:home_controller --new-shopify-cli-app
┃       create  app/controllers/home_controller.rb
┃     generate  shopify_app:products_controller
┃        rails  generate shopify_app:products_controller
┃       create  app/controllers/products_controller.rb
┃        route  get '/products', :to => 'products#index'
┃       create  app/views/home/index.html.erb
┃        route  root :to => 'home#index'
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (88.64s) ━━
┏━━ Running migrations… ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ Created database 'db/development.sqlite3'
┃ Created database 'db/test.sqlite3'
┃ == 20220528005747 CreateShops: migrating ======================================
┃ -- create_table(:shops)
┃    -> 0.0100s
┃ -- add_index(:shops, :shopify_domain, {:unique=>true})
┃    -> 0.0008s
┃ == 20220528005747 CreateShops: migrated (0.0109s) =============================
┃
┃ == 20220528005748 AddShopAccessScopesColumn: migrating ========================
┃ -- add_column(:shops, :access_scopes, :string)
┃    -> 0.0096s
┃ == 20220528005748 AddShopAccessScopesColumn: migrated (0.0096s) ===============
┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (27.17s) ━━
┏━━ Error ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ ✗ Error installing rails gem
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

**Closed** 2022-09-05 04:17 UTC
Labels: type:bug, no-issue-activity, status:waiting-for-feedback
