### ISSUE TITLE
Fonts are not pulling

### ISSUE THREAD

**Issue by davodavodavo3** [Shopify/shopify-cli#1396] opened 2021-07-17 12:07 UTC
# Issue summary

Using shopify CLI the pull when having custom font's in assets is trigerring error and not downloading theme font's

## Expected behavior

Theme font's need to be downloaded.

## Actual behavior

┃ ERROR get assets/Arial-Bold.eot: wrong number of arguments (given 4, expected 2..3)
┃ ERROR get assets/Arial-Bold.ttf: wrong number of arguments (given 4, expected 2..3)
┃ ERROR get assets/Arial-Bold.woff2: wrong number of arguments (given 4, expected 2..3)
┃ ERROR get assets/Arial-Bold.woff: wrong number of arguments (given 4, expected 2..3)
┃ ERROR get assets/Arial.eot: wrong number of arguments (given 4, expected 2..3)
┃ ERROR get assets/Arial.ttf: wrong number of arguments (given 4, expected 2..3)
┃ ERROR get assets/Arial.woff2: wrong number of arguments (given 4, expected 2..3)
┃ ERROR get assets/Arial.woff: wrong number of arguments (given 4, expected 2..3)

![image](https://user-images.githubusercontent.com/10462563/126036332-b70a052b-625a-460a-af71-565bac083ad7.png)

## Steps to reproduce the problem

1. Add font's in assets folder and push theme
2. Pull curently pushed theme and the error will trigger

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

## Specifications

- App type:
- Operating System: Windows 10
- Shell: PowerShell
- Ruby version (ruby -v): ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x64-mingw32]

**Comment by macournoyer** [comment] 2021-11-02 19:31
Closing as duplicate of #1360, which should now be fixed.

**Closed by macournoyer** 2021-11-02 19:31 UTC
Labels: area:theme
