### ISSUE TITLE
Error: Not authorized as Store Owner when running shopify theme serve

### ISSUE THREAD

**Issue by davecyen** [Shopify/shopify-cli#1332] opened 2021-07-02 14:44 UTC
# Issue summary

Write a short description of the issue here ↓

I'm following the Getting Started tutorial on `https://shopify.dev/themes/getting-started/create`. 

I successfully created a development store as a partner org, but when I attempted to run `shopify theme serve` in the CLI, I received an error that I wasn’t authorized to edit this theme (even though I was logged in as the owner of the store). 

<details>✗ You are not authorized to edit themes on [STORE].
Make sure you are a user of that store, and allowed to edit themes.</details>

As a workaround, I created a new Staff User account using an alternate email address, and then logged out as the Store Owner and logged back in using the Staff Account via the CLI. This allowed me to run `shopify theme serve` successfully. 

## Specifications

- App type: Theme, CLI
- Operating System: macOS 11.4
- Shell: `/bin/zsh`
- Ruby version (ruby -v): ruby 2.6.3p62 (2019-04-16 revision 67580)

**Comment by codingphasedotcom** [comment] 2021-07-04 04:02
I just had to do the same thing to get past this bug. Even though I'm the store owner I had to create another account and make it a staff account to the store. Then give it permission to everything on the store (which the store owner should have by default) fot the command ```shopify theme serve``` to work.

**Comment by pveen2** [comment] 2021-07-05 13:31
Same over here, would be great if this can be fixed!

**Comment by jondisla** [comment] 2021-07-05 17:58
The same workaround worked for me, create a staff member (used a different email address than admin) > logged in with that new email > also logged in using the CLI with the new email > shopify theme serve worked fine.

**Comment by tangar76** [comment] 2021-07-06 12:49
I had the same problem with my dev store. When logged in as store owner I got error:

```
✗ You are not authorized to edit themes on [domian-name].
Make sure you are a user of that store, and allowed to edit themes.
```

Only new staff member account worked.

**Comment by macournoyer** [comment] 2021-07-06 19:08
Sorry about this everyone! No concrete progress on this yet.

Another workaround is to log in through the store `/admin` once. Afterwards everything should work with the owner account.

We're looking at a proper fix.

**Comment by macournoyer** [comment] 2021-07-06 19:12
Closing as a duplicate of #1309

**Closed by macournoyer** 2021-07-06 19:12 UTC

**Comment by wwwisie** [comment] 2021-07-11 19:12
> Sorry about this everyone! No concrete progress on this yet.
> 
> Another workaround is to log in through the store `/admin` once. Afterwards everything should work with the owner account.
> 
> We're looking at a proper fix.

This worked for me.

**Comment by makasanas** [comment] 2021-07-21 10:25
It is solved by Creating new staff account on another email and log in by it.

**Comment by TGIFelix** [comment] 2021-07-21 15:16
None of the solutions above solved this issue for me.

**Comment by trenkwill** [comment] 2021-07-21 16:25
it's still buggy. I went back to Themekit..

**Comment by danboyle8637** [comment] 2021-07-21 23:49
Yikes. This was a headache. But I logged out of the cli... logged out of the web dashboard. Went directly to the store url with `/admin` on... logged in. 

Logged back into the cli... 

And this is probably superstitious... but I didn't close the window that said I was logged in. Haha!

Ran `shopify theme serve` and wouldn't you know... it worked.

I have no rhyme or reason.

**Comment by alxv2016** [comment] 2021-07-23 01:04
> Yikes. This was a headache. But I logged out of the cli... logged out of the web dashboard. Went directly to the store url with `/admin` on... logged in.
> 
> Logged back into the cli...
> 
> And this is probably superstitious... but I didn't close the window that said I was logged in. Haha!
> 
> Ran `shopify theme serve` and wouldn't you know... it worked.
> 
> I have no rhyme or reason.

This was the only workaround that worked. If anyone stumbles on this issue try this. Thanks!

**Comment by gnoem** [comment] 2021-08-17 22:39
> Yikes. This was a headache. But I logged out of the cli... logged out of the web dashboard. Went directly to the store url with `/admin` on... logged in.
> 
> Logged back into the cli...
> 
> And this is probably superstitious... but I didn't close the window that said I was logged in. Haha!
> 
> Ran `shopify theme serve` and wouldn't you know... it worked.
> 
> I have no rhyme or reason.

this worked for me!

**Comment by jonpennington** [comment] 2021-09-03 07:55
Same for me too. Is there any update on addresssing this?

**Comment by AbdullahDiaa** [comment] 2021-09-06 17:38
> This does not work for me ... -_-
> When will we get a fix ?
> We have to be able to work on our stores through the partner account auth

You can follow instructions mentioned in this video to make it work:
https://youtu.be/CFSmlLfh6FE?t=237

**Comment by thecoolagency** [comment] 2021-09-25 23:47
> Yikes. This was a headache. But I logged out of the cli... logged out of the web dashboard. Went directly to the store url with `/admin` on... logged in.
> 
> Logged back into the cli...
> 
> And this is probably superstitious... but I didn't close the window that said I was logged in. Haha!
> 
> Ran `shopify theme serve` and wouldn't you know... it worked.
> 
> I have no rhyme or reason.

That just worked wonders for me, just had to logout from my browser as well, the login to the cli.

**Comment by predevsign** [comment] 2021-10-22 23:57
> Yikes. This was a headache. But I logged out of the cli... logged out of the web dashboard. Went directly to the store url with `/admin` on... logged in.
> 
> Logged back into the cli...
> 
> And this is probably superstitious... but I didn't close the window that said I was logged in. Haha!
> 
> Ran `shopify theme serve` and wouldn't you know... it worked.
> 
> I have no rhyme or reason.

wow, that actually worked. Thanks a bunch. I'm over here reading the Shopify-CLI docs and was wondering wtf going on lol. Thanks again!

**Comment by Workoutproblems** [comment] 2021-11-28 02:44
> Sorry about this everyone! No concrete progress on this yet.
> 
> Another workaround is to log in through the store `/admin` once. Afterwards everything should work with the owner account.
> 
> We're looking at a proper fix.

Did this in a new incognito window and updated the store to my account, was able to use CLI after.

**Comment by EktaMerai** [comment] 2021-12-03 11:48
> > This does not work for me ... -_-
> > When will we get a fix ?
> > We have to be able to work on our stores through the partner account auth
> 
> You can follow instructions mentioned in this video to make it work: 📹 https://youtu.be/CFSmlLfh6FE?t=237

Thank you so much this video is very helpful.This solution works for me

**Comment by b4thestorm** [comment] 2021-12-18 05:38
Superbly random, but after trying for a bit I was able to get it up. 
followed, the logout, login directly to admin. But.... One thing that was different was
after a while of trying the same thing, shopify asked me to make a Shopify ID. 
after I made that, I was kicked over to the Admin. When I went back to the CLI, it magically worked.

**Comment by darnomccode** [comment] 2022-01-04 19:23
I followed your advice and really appreciate it. I created a new account, logged out, logged in as the new account and it worked. Now I can sync from my local environment.

**Comment by mateusdiasdev** [comment] 2022-01-05 21:17
Well, trying to follow some of the advices given in this "issue" I found that I have created with the admin account of the company and while trying to use `shopify theme serve` with my own company account, so that is why I need to create a staff inside the store with **my own company email**. This way things worked out.

**Comment by yashsony** [comment] 2022-01-22 10:54
> > This does not work for me ... -_-
> > When will we get a fix ?
> > We have to be able to work on our stores through the partner account auth
> 
> You can follow instructions mentioned in this video to make it work: 📹 https://youtu.be/CFSmlLfh6FE?t=237

It worked

**Comment by ecupaio** [comment] 2022-02-02 18:57
> You can follow instructions mentioned in this video to make it work: 📹 https://youtu.be/CFSmlLfh6FE?t=237
@AbdullahDiaa 

To re-iterate from the [video]( https://youtu.be/CFSmlLfh6FE?t=237) and write it down for people hard of hearing:   
Assuming you have a partner login and you have created a store under that partner login: 

1. Logout of your store, by entering `shopify logout` in your terminal
2. Open your store admin `YOURSTORE.myshopify.com/admin` and select logout to be completely logged out.
3. Open your store admin again: `YOURSTORE.myshopify.com/admin` and enter the same account info you used to create the store. 
4. Now back at your terminal, enter `shopify login --store=ec-dawn-test.myshopify.com` and select your partner organization.
5. A browser window will open and prompt you to select an account. Login with the same email that you use for your partner account and the store you created.
6. You will see a message that you are now authorized. 
7. Run `shopify theme serve` and the Shopify CLI should load up and start running. 

If you have any issues with these instructions, please tag me and let me know. A special shout out to @AbdullahDiaa for figuring out the workaround.

**Comment by chorbster** [comment] 2022-02-10 03:00
> > This does not work for me ... -_-
> > When will we get a fix ?
> > We have to be able to work on our stores through the partner account auth
> 
> You can follow instructions mentioned in this video to make it work: 📹 https://youtu.be/CFSmlLfh6FE?t=237

Thanks this has worked for me after trying alot of stuff

**Comment by arunmecom** [comment] 2022-04-06 11:16
I was facing the same issue
What I did
1: Log in to /admin and clear cookies
2: re-enter my login and password for the store
3: tried shopify login --store=[store] and shopify theme serve
4: and it worked

We have only one solution using /admin but still, people facing issues because of cookies, please try after removing cookies from the admin browser

**Comment by petercampanelli** [comment] 2022-04-13 17:34
@AbdullahDiaa's solution works if the owner of the Partner dashboard is an Owner, Staff, or Collaborator for a store. But, what about if I have other users on my Partner dashboard that might not have direct access to the store (their own login)? They can log into the Shopify Admin through the Partner dashboard, but not through "/admin".

**Comment by thediep094** [comment] 2022-07-18 15:10
> 

it worked for me. Thanks u so much

**Comment by henryobiaraije** [comment] 2022-08-06 12:43
> Yikes. This was a headache. But I logged out of the cli... logged out of the web dashboard. Went directly to the store url with `/admin` on... logged in.
> 
> Logged back into the cli...
> 
> And this is probably superstitious... but I didn't close the window that said I was logged in. Haha!
> 
> Ran `shopify theme serve` and wouldn't you know... it worked.
> 
> I have no rhyme or reason.

This did work for me.

**Comment by BrandonLandgraff** [comment] 2022-11-06 17:43
> Sorry about this everyone! No concrete progress on this yet.
> 
> Another workaround is to log in through the store `/admin` once. Afterwards everything should work with the owner account.
> 
> We're looking at a proper fix.

This worked for me - I had to sign in through incognito though!

**Comment by alistairholt** [comment] 2022-11-23 17:57
Over a year later and we still have to use a workaround 🤣

**Comment by dashy2021** [comment] 2022-12-07 12:04
Step 1: shopify logout
Step 2: shopify login --store <DOMAIN>
Step 3: Shopify theme serve


Works for me
