### ISSUE TITLE
shopify app serve failed

### ISSUE THREAD

**Issue by tanjir-mahabub** [Shopify/shopify-cli#1802] opened 2021-11-25 23:35 UTC
PS F:\test\app> shopify app serve
√ curl @ C:/Windows/System32/curl.EXE
√ tar @ C:/Windows/System32/tar.EXE
√ Installing ngrok…
X Something went wrong with ngrok installation,please make sure ngrok.exe exists within C:/Users/user/AppData/Local/shopify before trying again

**Comment by nihanmubashshir** [comment] 2021-12-01 14:42
I am using Ubuntu.
I have found that the official link that Shopify CLI uses to download ngrok is really slow. LIke 12kb/s slow (I have checked my net speed nothing wrong there). So, if you have stopped Shopify CLI thinking it's not working this is what happens:

1. It's downloading the ngrok files.
2. You stop the process since it's taking too long. But partial parts get downloaded.
3. Next time when you try, Shopify sees that the file is already there, so instead of downloading ngrok it simply tries to unpack that faulty file but then the error occurs and everything stops.

Solution: Follow this line: X Something went wrong with ngrok installation,please make sure ngrok.exe exists within C:/Users/user/AppData/Local/shopify before trying again. Actually download the ngrok and upack at that destination. And run  the CLI tool, everything should be fine.

**Comment by gonzaloriestra** [comment] 2021-12-03 08:26
Duplicate of https://github.com/Shopify/shopify-cli/issues/1776

**Comment by tanjir-mahabub** [comment] 2021-12-03 08:36
Shopify-cli 2.7.0 is running perfectly

**Comment by gonzaloriestra** [comment] 2022-02-16 13:56
@tanjir-mahabub sorry for the late response. I'm closing here since the original issue seems to be fixed. If you still have any kind of problem, please let me know.

**Closed by gonzaloriestra** 2022-02-16 13:56 UTC
Labels: area:ngrok
