### ISSUE TITLE
Shopify CLI not working as expected for store owner user

### ISSUE THREAD

**Issue by denis-tanksoft** [Shopify/shopify-cli#1313] opened 2021-06-30 13:52 UTC
# Issue summary

If I logged in via "shopify login" as store owner but not as a store staff 
all off commands like "shopify theme pull" or "shopify theme serve" return an error

## Expected behavior
should work like described in documentation

## Actual behavior

What actually happens?

I've got en error:
megazoid@MacBook-Pro % shopify theme pull
This command ran with ID: 34125
Please include this information in any issues/report along with relevant logs
/usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/lib/shopify-cli/api.rb:72:in `block in request': 403 (ShopifyCli::API::APIRequestForbiddenError)
{"errors":"Unauthorized Access"}

## Steps to reproduce the problem

1. Create a new store (2.0) 
2. shopify login --store=[STORE] using your account where you are a store owner only
3. shopify theme pull

**Comment by macournoyer** [comment] 2021-06-30 17:16
Duplicate of #1309

**Closed by macournoyer** 2021-06-30 17:16 UTC
