### ISSUE TITLE
Shopify Theme Server Error 2.7/ffi_c on WSL2

### ISSUE THREAD

**Issue by johndugan** [Shopify/shopify-cli#1405] opened 2021-07-23 20:36 UTC
# Issue summary

After running `shopify theme serve` I get an error: `[LoadError] cannot load such file -- 2.7/ffi_c`

## Expected behavior

no load errors

## Actual behavior

After theme synchronization, below the theme links I see:

```
[Note] You cannot use gems with Shopify CLI.
[LoadError] cannot load such file -- 2.7/ffi_c
       They are disabled.
       Please don't modify the CLI locally.
       If you would like to contribute to the CLI project, please refer to
       https://github.com/Shopify/shopify-cli/blob/main/.github/CONTRIBUTING.md
```

## Steps to reproduce the problem

1. run `shopify theme serve`

## Specifications

- App type: store theme
- Shopify CLI version: `2.1.0`
- Operating System: WSL2 Ubuntu on Windows 10.0.19042 Build 19042
- Shell: Bash
- Ruby version (ruby -v): `ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]`

**Comment by cbepxpa3ym** [comment] 2021-07-24 18:49
I have the same issue.

**Comment by anhez** [comment] 2021-07-25 03:16
I have the same issue too

**Comment by this-geek** [comment] 2021-08-06 22:39
Can confirm this is present on the new CLI as well.  CLI is 2.2.0, running WSL2 Ubuntu 20.4.

**Comment by Powellze** [comment] 2021-08-07 17:51
Getting the same issue with WSL + CLI2.2 anyone managed to resolve this?

**Comment by Powellze** [comment] 2021-08-08 11:43
Thanks @gomarion 
I've found issues with Shopify CLI in windows not sending up all assets which is why I've switched to WSL.
I'm in between two pain points at the moment.

I've tried a few more things to try and get to the bottom of this.
* Debian + Ubunutu
* Ruby 2.7 + 3.0
* RVM + RBENV
* Shopify CLI 2.1.0, 2.2.0
Always the same issue so far, just comes up with a different version of FFI_C is the problem

**Comment by gomarion** [comment] 2021-08-09 04:54
@Powellze I can confirm this as well. I tried different versions of Ruby and Gems via RVM, also tried different flavors in WSL (Arch and Ubuntu) and still experience the same issue with FFI_C. I'm pretty sure this has worked in the past because the Shopify team specifically mentioned WSL as our option in Windows. So it could be either that this is a recent issue or they could have overlooked the 'theme serve' aspect of it.

I haven't tried out serving assets yet (SVG ang images) using the Windows installer since I've just recently tried out setting up the theme, but I'll see if this is also the same case in my end.

**Comment by Powellze** [comment] 2021-08-10 13:30
Switching the default to WSL1 for all distro's seems to have worked to a point that I can now make changes to the theme and manually reload the page to view the changes. Any changes to the assets directory don't get picked up by the reload script.

Set all distros to WSL1:
* wsl --set-default-version 1 

Set a singular distro to WSL1:
* wsl --set-version <distro name> 1

Hope this helps a little until it's properly resolved.

**Comment by oneezy** [comment] 2021-09-06 23:53
same issue on this end. Why is this happening @shopify-admins ??? it's been **45 days** and not one shopify team member has been assigned or even responded. Come on guys... Please hold true to the _"Investing In Developers"_ catch phrase. This kind of stuff should already be flushed out if you're pushing the CLI out for production. I'm not trying to complain but I'm a little upset about the Shopify developer onboarding experience

@macournoyer @jplhomer @mllemango @mkevinosullivan @jacobsteves @tylerball @tleunen @haeky @katiedavis @iaserrat @paulomarg @fredericboivin @ow @gfscott

**Comment by macournoyer** [comment] 2021-09-08 12:40
Thanks!

@oneezy what version of the CLI are you using in this video? I suspect the message might just be a red herring in the latest version.

@this-geek Now that you're on version 2.3 of the CLI, can you confirm if the preview is updated in the browser after you edit a file?

**Comment by this-geek** [comment] 2021-09-08 22:03
Hey @macournoyer,
yes, sorry it was not clearer.  As per @oneezy, there is no live reload.  I needed to stop and restart the cli command to get changes previewed.
Cheers

**Comment by macournoyer** [comment] 2021-09-16 23:28
Should be fixed by https://github.com/Shopify/shopify-cli/pull/1542. But it will require you to pass the `--poll` option under WSL2.

`shopify theme serve --poll`

**Comment by hardikdangar** [comment] 2021-09-18 09:00
@macournoyer I am getting following error on running --poll option,


`This command ran with ID: 87451
Please include this information in any issues/report along with relevant logs
Traceback (most recent call last):
	24: from /var/lib/gems/2.7.0/gems/shopify-cli-2.3.0/bin/shopify:32:in `<main>'
	23: from /var/lib/gems/2.7.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	22: from /var/lib/gems/2.7.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	21: from /var/lib/gems/2.7.0/gems/shopify-cli-2.3.0/bin/shopify:33:in `block in <main>'
	20: from /var/lib/gems/2.7.0/gems/shopify-cli-2.3.0/lib/shopify-cli/core/entry_point.rb:23:in `call'
	19: from /var/lib/gems/2.7.0/gems/shopify-cli-2.3.0/lib/shopify-cli/core/monorail.rb:20:in `log'
	18: from /var/lib/gems/2.7.0/gems/shopify-cli-2.3.0/lib/shopify-cli/core/entry_point.rb:24:in `block in call'
	17: from /var/lib/gems/2.7.0/gems/shopify-cli-2.3.0/lib/shopify-cli/core/executor.rb:15:in `call'
	16: from /var/lib/gems/2.7.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
	15: from /var/lib/gems/2.7.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
	14: from /var/lib/gems/2.7.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	13: from /var/lib/gems/2.7.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
	12: from /var/lib/gems/2.7.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
	11: from /var/lib/gems/2.7.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
	10: from /var/lib/gems/2.7.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
	 9: from /var/lib/gems/2.7.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
	 8: from /var/lib/gems/2.7.0/gems/shopify-cli-2.3.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
	 7: from /var/lib/gems/2.7.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
	 6: from /var/lib/gems/2.7.0/gems/shopify-cli-2.3.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
	 5: from /var/lib/gems/2.7.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
	 4: from /var/lib/gems/2.7.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
	 3: from /var/lib/gems/2.7.0/gems/shopify-cli-2.3.0/lib/shopify-cli/command.rb:19:in `call'
	 2: from /var/lib/gems/2.7.0/gems/shopify-cli-2.3.0/lib/shopify-cli/sub_command.rb:9:in `call'
	 1: from /var/lib/gems/2.7.0/gems/shopify-cli-2.3.0/lib/shopify-cli/options.rb:19:in `parse'
/var/lib/gems/2.7.0/gems/shopify-cli-2.3.0/lib/shopify-cli/options.rb:28:in `parse_flags': invalid option: --poll (OptionParser::InvalidOption)
`

**Comment by SimJWalter** [comment] 2021-09-18 09:04
@hardikdangar it wont work yet, the change has to be reviewed, accepted, merged into the cli then released in to the installer package

**Comment by Powellze** [comment] 2021-09-18 09:10
> Should be fixed by #1542. But it will require you to pass the `--poll` option under WSL2.
> 
> `shopify theme serve --poll`

@macournoyer Thank you - once released we will adjust our dev process to use this.
The readme.md to include the new switch - is this something you need help with or do you and the team have it covered?

Looks like this should be added under 3.- Start the local theme server as a warning for windows WSL users to ensure they use the new --poll

**Comment by SimJWalter** [comment] 2021-09-18 09:19
@macournoyer @Powellze 
isn't there a way to check for the WSL version when the process starts up and switch polling on for WSL2?  If the polling works then it seems like a satisfactory solution

**Comment by wesley6j** [comment] 2021-09-25 01:51
This load error does not directly cause any real problems. Please check [here](https://github.com/ffi/ffi/blob/50098f2f03b1220df8d48c2f8bc94af05f1b4951/lib/ffi.rb#L2), ffi will require 'ffi_c' instead.

```ruby
begin
  require RUBY_VERSION.split('.')[0, 2].join('.') + '/ffi_c'
rescue Exception
  require 'ffi_c'
end
```

**Closed** 2021-10-05 17:32 UTC
Labels: area:dev-environment
