### ISSUE TITLE
Getting error: The access token provided is expired, revoked, malformed, or invalid for other reasons.

### ISSUE THREAD

**Issue by zinyosrim** [Shopify/shopify-cli#1338] opened 2021-07-05 11:36 UTC
# Issue summary
When using `shopify node create` or `shopify login` or `shopify node serve`I'm getting an error message.
I already created an app und was already running it. Got the error after restarting my PC

## Expected behavior
Commands should execute properly

## Actual behavior

What actually happens?
`shopify node serve`
Please provide this information with your report:
www-authenticate: Bearer realm="271e16d403dfa18082ffb3d197bd2b5f4479c3fc32736d69296829cbb28d41a6",error="invalid_token",error_description="The access token provided is expired, revoked, malformed, or invalid for other reasons."
x-request-id: 6f0afed262312250c3ff29c65d401958

## Specifications

- App type: custom
- Operating System: Mac OS 11.0.1
- Shell: z-shell, hyper, iTerm2
- Ruby version (ruby -v): ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]

**Comment by djnorrisdev** [comment] 2021-07-05 11:59
Same problem when using `shopify login` this morning (everything worked yesterday). Thought running `shopify logout` then login again would resolve it, but it does not.

Specs:
App Type: Dawn theme clone
OS: Ubuntu 20.04.2 LTS 64-bit (native linux)
Gnome vers: 3.36.8
CLI installed with apt

**Comment by VladimirCatrici** [comment] 2021-07-05 12:01
Same here, I think many people reporting this here: https://github.com/Shopify/shopify-cli/issues/1285

**Comment by macournoyer** [comment] 2021-07-06 19:02
Closing as a duplicate of #1285.

We made some progress on this. https://github.com/Shopify/shopify-cli/issues/1285#issuecomment-874860396

Thanks for your patience everyone!

**Closed by macournoyer** 2021-07-06 19:02 UTC
