### ISSUE TITLE
Shopify theme --json - broken json when errors 

### ISSUE THREAD

**Issue by tommypepsi** [Shopify/shopify-cli#1417] opened 2021-07-29 15:44 UTC
# Issue summary

When running something like ```shopify theme push --json``` if there's an error during the push the error is outside of the json output making it an invalid json if you are capturing the output to run something else afterward. 

## Expected behavior

Errors should be part of the json output:

```
{
  "theme": {
    "id": 12345,
    "name": "theme",
    "role": "development",
    "shop": "something.myshopify.com",
    "editor_url": "https://something.myshopify.com/admin/themes/12345/editor",
    "preview_url": "https://something.myshopify.com/?preview_theme_id=12345",
    "errors": [
        {
          "type": "update",
          "filename": "template/404.json",
          "message": "missing required key 'order'"
        }
      ]
    }
  }
}
```

## Actual behavior

The output looks like that:

```
ERROR update templates/404.json:
  missing required key 'order'
{
  "theme": {
    "id": 12345,
    "name": "theme",
    "role": "development",
    "shop": "something.myshopify.com",
    "editor_url": "https://something.myshopify.com/admin/themes/12345/editor",
    "preview_url": "https://something.myshopify.com/?preview_theme_id=12345"
  }
}
```

## Steps to reproduce the problem

1. remove the "order" parameter from a json template.
2. run ``` shopify theme push --json```

## Specifications

- App type: Theme
- Operating System: Windows 10
- Shell: Powershell 
- Ruby version (ruby -v): 2.7.3p183

**Comment by stephszeto** [comment] 2021-09-10 00:39
Related: https://github.com/Shopify/shopify-cli/issues/1353

**Comment by macournoyer** [comment] 2021-11-02 18:58
Closing as duplicate of #1353

**Closed by macournoyer** 2021-11-02 18:58 UTC
Labels: area:theme
